CREATE TABLE USERS (LOGIN VARCHAR(255) PRIMARY KEY, HASH_PASSWORD VARCHAR(255), SALT VARCHAR(255));
CREATE TABLE RESOURCES (LOGIN VARCHAR(255) PRIMARY KEY, RESOURCE VARCHAR(255), ROLE VARCHAR(255));
CREATE INDEX INDEX_LOGIN_ROLE ON RESOURCES(LOGIN, ROLE);
CREATE TABLE ACCOUNTS (LOGIN VARCHAR(255) PRIMARY KEY, DATE_IN DATE, DATE_OUT DATE, VOLUME INT);